### ISSUE TITLE
configure it just for farm

### ISSUE THREAD

**Issue by gallardovsky** [d-haxton/HaxtonBot#106]
can the bot be configure just for farming pokemons, i write this couse, it always get the 200xp for catching any pokemon but i just want to farm not to lvl up that fast, how can i configure it?

**Comment by ComputerDavid** [comment]
Hi.  First, figure out what you DON'T want the bot to do.  Then edit the config file and/or the User Settings files.

For example, if you don't want a lot of XP then I would first make sure it wasn't using the Lucky Egg. So I would turn that off, aka "false" in the main config file.

You can tell the bot what pokemon to avoid.  I have mine avoid everything but Dratini, Dragonair, and Magikarp.  I only want THOSE pokemon because I really want a Dragonite and Gyrados.  It will take a while, but I don't want to level up that fast, already level 30.   It looks like this:
[URL=http://s1222.photobucket.com/user/PandaMarketer/media/1-pokemon-found.png.html][IMG]http://i1222.photobucket.com/albums/dd492/PandaMarketer/1-pokemon-found.png[/IMG][/URL]

The following is a list of all the pokemon in the game, take out what you want to farm, like I did:
Bulbasaur
Ivysaur
Venusaur
Charmander
Charmeleon
Charizard
Squirtle
Wartortle
Blastoise
Caterpie
Metapod
Butterfree
Weedle
Kakuna
Beedrill
Pidgey
Pidgeotto
Pidgeot
Rattata
Raticate
Spearow
Fearow
Ekans
Arbok
Pikachu
Raichu
Sandshrew
Sandslash
NidoranFemale
Nidorina
Nidoqueen
NidoranMale
Nidorino
Nidoking
Clefairy
Clefable
Vulpix
Ninetales
Jigglypuff
Wigglytuff
Zubat
Golbat
Oddish
Gloom
Vileplume
Paras
Parasect
Venonat
Venomoth
Diglett
Dugtrio
Meowth
Persian
Psyduck
Golduck
Mankey
Primeape
Growlithe
Arcanine
Poliwag
Poliwhirl
Poliwrath
Abra
Kadabra
Alakazam
Machop
Machoke
Machamp
Bellsprout
Weepinbell
Victreebel
Tentacool
Tentacruel
Geodude
Graveler
Golem
Ponyta
Rapidash
Slowpoke
Slowbro
Magnemite
Magneton
Farfetchd
Doduo
Dodrio
Seel
Dewgong
Grimer
Muk
Shellder
Cloyster
Gastly
Haunter
Gengar
Onix
Drowzee
Hypno
Krabby
Kingler
Voltorb
Electrode
Exeggcute
Exeggutor
Cubone
Marowak
Hitmonlee
Hitmonchan
Lickitung
Koffing
Weezing
Rhyhorn
Rhydon
Chansey
Tangela
Kangaskhan
Horsea
Seadra
Goldeen
Seaking
Staryu
Starmie
MrMime
Scyther
Jynx
Electabuzz
Magmar
Pinsir
Tauros
Magikarp
Gyarados
Lapras
Ditto
Eevee
Vaporeon
Jolteon
Flareon
Porygon
Omanyte
Omastar
Kabuto
Kabutops
Aerodactyl
Snorlax
Articuno
Zapdos
Moltres
Dratini
Dragonair
Dragonite
Mewtwo
Mew
