### ISSUE TITLE
How to 500k exp/h

### ISSUE THREAD

**Issue by mariobros33** [d-haxton/HaxtonBot#129]
Can someone put the coords please

**Comment by TurntKFC** [comment]
it depends on your profile... the best place i d say is central park, new york 40.77714 -73.96862, or san francisco 37.76787 -122.46834...

**Comment by snyy** [comment]
yes custom gpx. files around central park look it up

**Comment by Breez3** [comment]
@snyy can you give/show me tutorial how to use custom gpx. araound central park??
do i only have to change "UseGpxPathing" value to "true" or there is another thing to do to make this happen??. thanks :)

**Comment by snyy** [comment]
sorry i have been so late to respond. i can help with that because my config came with one. BUT you can get my config that has it. 180k-250k xp/h amd 600+ p/h. it comes with the gpx. file included so all you have to do is put in your username and pass. you can click here or go to my post and click it from there at the bottom thanks.http://www.ownedcore.com/forums/pokemon-go/pokemon-go-hacks-cheats/570533-haxton-config-high-level-botting-200k-h-no-eggs-easy-set-up.html  go here and follow the steps

**Comment by snyy** [comment]
also 500k now is unobtainable btw. the most i can get with the best configs out there is 280k at best

**Comment by icecubeice** [comment]
Earlier I had reached 300-350k in Central Park but it's down to 250k now
