### ISSUE TITLE
How do I get this running from master?

### ISSUE THREAD

**Issue by Hunter926** [d-haxton/HaxtonBot#61]
Ive tried opening the .sln in Visual Studio, but I keep getting errors that I don't know how to fix. I did get the missing references but still no dice..
Can anyone help with this issue? It would be greatly appreciated

[Screenshot of Errors](https://gyazo.com/e038f17259a5fa153709432fee942a97)

**Comment by kade-robertson** [comment]
You have posted this on the wrong project. You are looking for [NecroBot's](https://github.com/NecronomiconCoding/NecroBot) GitHub page.

**Comment by Hunter926** [comment]
Sorry I had the question for both bots haha. 
I'd still like to know how to get it running if someone could offer any assistance

**Comment by Zedilurk** [comment]
If you have visual studio, which since this is not a release build but rather the source files, you may need to do a little set up. When the project opens, you should get a Solution Explorer (most likely on the right side of your screen). Long story short, your solution is your project and the solution explorer is your browser window through all the files and settings. If you click the very top entry (Solution 'Haxton.PokemonGo Bot' (3 projects) and select "Properties," you'll get a pop up window. Under the Common Properties drop down on the left, there is a "Startup Project" option. This basically tells Visual Studio what project it should launch by default. In order to launch the project though, it needs a launching point, which requires the file "Program.cs". 

This file can be found in the "PokemonGo.Haxton.Console" project. So after you've selected the Startup Project option on the left side of the pop up window, make sure "Single startup project" is selected, and use the drop down to select "PokemonGo.Haxton.Console".

At this point, if you hit the "Start" button, the project should compile and run as normal. If not, you may have some errors in the repo you downloaded. 

See if that helps any.
